---
title: "REDD+ Nesting Feasibility"
author: "Winrock Intl"
date: "`r Sys.Date()`"
subtitle: "Scoping potential of nested REDD+ markets with risk-allocated deforestation mapping"
output:
  pdf_document:
    toc: true
    toc_depth: 4

always_allow_html: TRUE
editor_options: 
  markdown: 
    wrap: 70
---

```{r setup, eval=T}
#| warning: false
#| message: false
#| error: false
#| echo: false

# unix commands for GDAL flushing
#devtools::install_github("r-spatial/sf", configure.args = c(
#  "--with-gdal-config=/opt/local/bin/gdal-config", 
#  "--with-proj-include=/opt/local/lib/proj9/include", 
#  "--with-proj-lib=/opt/local/lib/proj9/lib", 
#  "--with-geos-config=/opt/local/bin/geos-config"))

#install.packages('terra', type="source", configure.args = c(
#  "--with-gdal-config=/opt/local/bin/gdal-config", 
#  "--with-proj-include=/opt/local/lib/proj9/include", 
#  "--with-proj-lib=/opt/local/lib/proj9/lib", 
#  "--with-geos-config=/opt/local/bin/geos-config"))

easypackages::packages(
  "animation", "allodb", "BIOMASS", "c2z", "caret", 
  "dataMaid", "DescTools","dplyr", "extrafont", 
  "FawR", "forestdata", "ForestToolsRS", "ggplot2", "giscoR", "ggmap", "geodata",
  "here", "htmltools", "janitor", "jsonlite", "lattice", 
  "kableExtra", "kernlab", "knitr", "Mlmetrics", 
  "osmdata", "plotly", "psych", 
  "RColorBrewer", "rmarkdown", "readxl", "rnaturalearth",
  "sf", "tibble", "tidymodels", "tidyverse", "tmap", "tmaptools",
  "useful", "webshot", "webshot2",
  prompt = F
  )

knitr::opts_chunk$set(
  echo    = TRUE, 
  message = FALSE, 
  warning = FALSE,
  error   = FALSE, 
  cache   = FALSE,
  comment = NA, 
  tidy.opts = list(width.cutoff = 60)
)

options(htmltools.dir.version = FALSE, htmltools.preserve.raw = FALSE)
sf::sf_use_s2(use_s2 = FALSE)
sf::sf_extSoftVersion()

# CCDF provides good tips on repo formatting here: https://rmi.org/carbon-crediting-data-framework/
```

----------------------------------------------------------------------

### Introduction

The following spatial covariates were imported as potential drivers of
deforestation risk. Covariates were merged between demographic and
geographic datasets surrounding the project area and national level
datasets beyond the project area in order to enable jurisdictional
analysis.

----------------------------------------------------------------------

### Import data

#### AOI Jurisdiction

```{r, class.source = c("numCode", "r", "numberLines")}
library(geodata)
library(tmaptools)
library(tmap)
library(sf)
sf::sf_extSoftVersion()
knitr::opts_knit$set(root.dir = here::here())

# AOI Jurisdictional Bdry 
aoi_country = geodata::gadm(country="ECU", level=0, path="./03_Spatial_Data/AOI") |> sf::st_as_sf()
aoi_states  = geodata::gadm(country="ECU", level=1, path="./03_Spatial_Data/AOI") |> sf::st_as_sf()
st_write(aoi_country, "./03_Spatial_Data/AOI/aoi_country.shp", delete_dsn = T)
st_write(aoi_states, "./03_Spatial_Data/AOI/aoi_states.shp", delete_dsn = T)
crs_master = sf::st_crs(aoi_country)

# Visualize
tmap::tmap_mode("plot")
tmap::tm_shape(aoi_country) + tmap::tm_borders(col="purple", lwd=2) +
  tmap::tm_shape(aoi_states) + tmap::tm_borders(col="purple", lwd=.5) +
  tmap::tm_scalebar(position=c("RIGHT", "BOTTOM"), text.size = .5) +
  tmap::tm_compass(color.dark="gray60",text.color="gray60",position=c("RIGHT", "top")) +
  tmap::tm_graticules(lines=T,labels.rot=c(0,90),lwd=0.2) +
  tmap::tm_layout(legend.position=c("left", "top"), legend.bg.color = "white") +
  tmap::tm_title("Risk Covariates Map: AOI Jurisdictional Boundaries", size=.8) + 
  tmap::tm_basemap("OpenStreetMap") 
  #tmap::tm_basemap("OpenTopoMap") 
  #tmap::tm_basemap("Esri.WorldImagery") 
```

----------------------------------------------------------------------

#### Built Environment

```{r, , class.source = c("numCode", "r", "numberLines"), eval=F}
library(osmdata)
library(httr2)
library(ggmap)

# Check OSM data & derive bbox window
osmdata::available_features()  
osmdata::available_tags("place")
aoi_bbox = osmdata::getbb("Ecuador")

# Hospitals
buildings_hospital = aoi_bbox |> osmdata::opq() |>
  osmdata::add_osm_feature(key = "amenity", value = "hospital") |>
  osmdata::osmdata_sf() # |> st_transform(crs_master)

# Housing
buildings_residential = aoi_bbox |> osmdata::opq() |>
  osmdata::add_osm_feature(key = "building", value = "residential") |>
  osmdata::osmdata_sf() # |> st_transform(crs_master)

# Religion
buildings_workship = aoi_bbox |> osmdata::opq() |>
  osmdata::add_osm_feature(key = "building", value = "religious") |>
  osmdata::osmdata_sf() 

# Towns 
townnames = aoi_bbox |> osmdata::opq() |>
  osmdata::add_osm_feature(key = "place", value = "town") |>
  osmdata::osmdata_sf()

# Villages
villages = aoi_bbox |> osmdata::opq() |>
  osmdata::add_osm_feature(key = "place", value = "village") |>
  osmdata::osmdata_sf()

# Merging collections
places_merged = townnames$osm_points |> bind_rows(villages$osm_points) |>
  group_by(across(-geometry)) |> sf::st_cast("POINT") |>
  summarise(geometry = st_union(geometry), .groups = "drop")
sf::st_write(places_merged, "./03_Spatial_Data/POP/places_merged.shp", delete_dsn=T) 

buildings_merged = buildings_hospital$osm_points |>
  bind_rows(buildings_residential$osm_points, buildings_workship$osm_points) |>
  group_by(across(-geometry)) |> sf::st_cast("POINT") |>
  summarise(geometry = st_union(geometry), .groups = "drop")
sf::st_write(buildings_merged, "./03_Spatial_Data/POP/buildings_merged.shp", delete_dsn=T) 

# Visualize
tmap::tm_shape(aoi_country) + tmap::tm_borders(col="purple", lwd=1) +
  tmap::tm_shape(aoi_states) + tmap::tm_borders(col="purple", lwd=.5) +
#  tmap::tm_shape(buildings_merged) + tmap::tm_symbols(size=0.15,lwd=0.5,fill="white",col="purple") +
#  tmap::tm_add_legend(type="symbols", col="white", fill="purple", size=0.8, labels="Buildings") +
  tmap::tm_shape(places_merged) + tmap::tm_symbols(size=0.2,lwd=0.5,fill="white",col="blue") +
  tmap::tm_add_legend(type="symbols", col="white", fill="blue", size=0.8, labels="Towns & Villages") +
  tmap::tm_scalebar(position=c("RIGHT", "BOTTOM"), text.size = .5) +
  tmap::tm_compass(color.dark="gray60",text.color="gray60",position=c("RIGHT", "top")) +
  tmap::tm_graticules(lines=T,labels.rot=c(0,90),lwd=0.2) +
  tmap::tm_layout(legend.position=c("left", "top"), legend.bg.color = "white") +
  tmap::tm_title("Risk Covariates Map: Built Environment", size=.8) + 
  tmap::tm_basemap("OpenStreetMap") 
  #tmap::tm_basemap("OpenTopoMap") 
  #tmap::tm_basemap("Esri.WorldImagery") 
```

----------------------------------------------------------------------

#### Transportation

```{r, eval=F, class.source = c("numCode", "r", "numberLines")}
# Motorway/Highways
transport_motorway <- aoi_bbox %>% opq() %>%
  add_osm_feature(key = "highway", value = "motorway") %>%
  osmdata_sf()

# Roads
transport_roads <- aoi_bbox %>% opq() %>%
  add_osm_feature(key = "XXXXXXX", value = "XXXXXXX") %>%
  osmdata_sf()

# Tracks
transport_tracks <- aoi_bbox %>% opq() %>%
  add_osm_feature(key = "XXXXXXX", value = "XXXXXXX") %>%
  osmdata_sf()

# Railways
transport_path <- aoi_bbox %>% opq() %>%
  add_osm_feature(key = "XXXXXXX", value = "XXXXXXX") %>%
  osmdata_sf()

# Merge all transport
transport_merged = transport_motorway |>
  bind_rows(transport_tracks, transport_path) |>
  group_by(across(-geometry)) |> sf::st_cast("MULTILINESTRING")
  summarise(geometry = st_union(geometry), .groups = "drop")
sf::st_write(transport_merged, "./03_Spatial_Data/Risk/transport_merged.shp", delete_dsn=T) 

# Visualize 
tmap::tm_shape(aoi_country) + tmap::tm_borders(col="green", lwd=3) +
  tmap::tm_shape(aoi_states) + tmap::tm_borders(col="orange") +
  tmap::tm_shape(buildings_merged) + tmap::tm_symbols(size=0.35,lwd=0.5,fill="",col="white") +
  tmap::tm_shape(transport_merged) + tmap::tm_symbols(size=0.35,lwd=0.5,fill="purple",col="white") +
  tmap::tm_add_legend(type="symbols", col="purple", fill="purple", size=0.8, labels="Buildings") +
  tmap::tm_scalebar(position=c("RIGHT", "BOTTOM"), text.size = .5) +
  tmap::tm_compass(color.dark="gray60",text.color="gray60",position=c("RIGHT", "top")) +
  tmap::tm_graticules(lines=T,labels.rot=c(0,90),lwd=0.2) +
  tmap::tm_layout(legend.position=c("left", "top"), legend.bg.color = "white") +
  tmap::tm_title("Risk Covariates Map: Built Environment", size=.8) + 
  tmap::tm_basemap("OpenStreetMap") 
  #tmap::tm_basemap("OpenTopoMap") 
  #tmap::tm_basemap("Esri.WorldImagery") 
```

----------------------------------------------------------------------

#### Hydrography

```{r, eval=F, class.source = c("numCode", "r", "numberLines")}
waterways_country = sf::st_read("./03_Spatial_Data/HYDRO/waterways_country.shp")  #|>
  #sf::st_intersection(aoi_bbox) |> 
  #dplyr::select(name,fclass) |>
  #dplyr::mutate(fclas=as.factor(fclass)) |> 
  #dplyr::mutate(name=as.character(name)) 

waterbodies_country = sf::st_read("./03_Spatial_Data/HYDRO/waterbodies_country.shp")
  sf::st_intersection(aoi_country) |>
  dplyr::select(name,fclass) |>
  dplyr::mutate(fclass=as.factor(fclass)) |> 
  dplyr::mutate(name=as.character(name)) 

water_merged = waterbodies_country |>
  bind_rows(waterbodies_poly_lines, waterways_merged) |>
  group_by(across(-geometry)) |>
  summarise(geometry=st_union(geometry), .groups="drop") 

water_merged = sf::st_cast(water_merged, "MULTILINESTRING") 
sf::st_write(water_merged, "./03_Spatial_Data/HYDRO/water_merged.shp", delete_dsn=T)
```

----------------------------------------------------------------------

#### Topography

```{r, eval=F, class.source = c("numCode", "r", "numberLines")}

##################################
##################################
##################################
dem = raster::subset(STACK, "DEM") 
##################################
##################################
##################################


slope_tangent = raster::terrain(dem,
  opt="slope",
  unit="tangent",
  neighbors=8,
  filename="./03_Spatial_Data/TOPO/slope_tangent.tif"
  )

slope_tangent = terra::rast("./03_Spatial_Data/TOPO/slope_tangent.tif")
slope_percent = slope_tangent * 100 
slope_percent = terra::clamp(slope_percent, 0, 100) 
slope_percent = raster::raster(slope_percent) 
raster::writeRaster(slope_percent,"./03_Spatial_Data/TOPO/slope_percent.tif", overwrite=T)
```

----------------------------------------------------------------------

### Risk-allocated deforestation

Two methods were explored for weighting variables and creating a
generalized deforestation risk index. For efficiency of time, we
adopted the following risk indexing approach, which was based on a
weighted sum of subjectively scored covariate effects. Please note
this approach was also recommended for its ease of updating in
subsequent iterations.

We applied this risk index to inform a risk weighted allocation of a
10-year deforestation rate, first by multiplying the fraction of pixel
risk by zonal forest loss, and second by factoring out annual zonal
loss by multiplying by pixel risk values, as shown below.[^1]

$$
\mathrm{AllocatedLoss}_{\mathrm{pixel}}
=
\left(
  \frac{\mathrm{risk}_{\mathrm{pixel}}}{\sum \mathrm{risk}_{\mathrm{zone}}}
\right)
\times
\mathrm{annual\_loss\_10yr}_{\mathrm{zone}}
$$

$$
\mathrm{allocated\_loss}_{\mathrm{pixel}}
=
\mathrm{risk}_{\mathrm{pixel}}
\times
\left(
  \frac{\mathrm{annual\_loss\_10yr}_{\mathrm{zone}}}{\sum \mathrm{risk}_{\mathrm{zone}}}
\right)
$$

Both formulas describe the same operation in different orders of
multiplication: each pixel in a given zone Z receives a share of
`annual_loss_10yr` based on its proportional risk. This ensures that
higher-risk pixels are allocated higher deforestation loss, which is
in line with Verra guidance regarding allocated deforestation risk
maps.

----------------------------------------------------------------------

#### Visualize Deforestation Risk

```{r, eval=F, class.source = c("numCode", "r", "numberLines")}
#### assemble covariates
states        = sf::st_read("./03_Spatial_Data/RISK/aoi_states.shp")
districts     = sf::st_read("./03_Spatial_Data/RISK/aoi_districts.shp")
places        = sf::st_read("./03_Spatial_Data/RISK/places_merged.shp")
buildings     = sf::st_read("./03_Spatial_Data/RISK/buildings_merged.shp")
transport     = sf::st_read("./03_Spatial_Data/RISK/transport_merged.shp")
waterways     = sf::st_read("./03_Spatial_Data/RISK/water_merged.shp")
slope         = stars::read_stars("./03_Spatial_Data/RISK/slope_percent.tif")


tmap::tmap_mode("plot")
tmap::tmap_arrange(tm3, tm4, tm6, tm5, ncols=2)
```

#### Visualize Deforestation Allocation

[^1]: We computed risk allocation based on each pixel's risk value
    relative to the sum of all pixel risks in that zone.
